version: '3.4'

services:
  seclog.api:
    image: ${DOCKER_REGISTRY-}seclogapi
    container_name: SecLog.API
    build:
      context: .
      dockerfile: SecLog.API/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: SecLog

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      -  ./SecLog.API/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - seclog.api
volumes:
  db-volume:
